default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  reconnect: false

development:
  <<: *default
  database: chat_app
  username: sooraj
  password: qburst
  host: localhost

test:
  <<: *default
  database: chat_app
  username: sooraj
  password: qburst
  host: localhost

production:
  <<: *default
  database: chat_app
  username: sooraj
  password: qburst
  host: localhost
